"""Configuration constants for codecontexter."""

# Language mapping from file extension/name to language name
LANGUAGE_MAP: dict[str, str | None] = {
    # Python
    ".py": "python",
    ".pyi": "python",
    ".pyx": "python",
    ".ipynb": "json",
    "pyproject.toml": "toml",
    "setup.py": "python",
    "requirements.txt": "text",
    "requirements-dev.txt": "text",
    "pipfile": "toml",
    "pipfile.lock": "json",
    "poetry.lock": "toml",
    "setup.cfg": "ini",
    "tox.ini": "ini",
    "pytest.ini": "ini",
    # JavaScript/TypeScript/Node
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".tsx": "tsx",
    "package.json": "json",
    "package-lock.json": "json",
    "tsconfig.json": "json",
    "jsconfig.json": "json",
    ".eslintrc": "json",
    ".eslintrc.json": "json",
    ".eslintrc.js": "javascript",
    ".prettierrc": "json",
    ".babelrc": "json",
    "babel.config.js": "javascript",
    "webpack.config.js": "javascript",
    "vite.config.js": "javascript",
    "vite.config.ts": "typescript",
    "next.config.js": "javascript",
    "nuxt.config.js": "javascript",
    "vue.config.js": "javascript",
    # Web
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "sass",
    ".less": "less",
    ".vue": "vue",
    ".svelte": "svelte",
    # Java & JVM
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".groovy": "groovy",
    ".gradle": "groovy",
    ".scala": "scala",
    "pom.xml": "xml",
    "build.gradle": "groovy",
    "build.gradle.kts": "kotlin",
    "settings.gradle": "groovy",
    "gradlew": "bash",
    "application.properties": "properties",
    "application.yml": "yaml",
    "application.yaml": "yaml",
    # C-family
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".m": "objective-c",
    ".mm": "objective-c",
    "CMakeLists.txt": "cmake",
    ".cmake": "cmake",
    # Other Languages
    ".go": "go",
    "go.mod": "go",
    "go.sum": "text",
    ".rs": "rust",
    "Cargo.toml": "toml",
    "Cargo.lock": "toml",
    ".rb": "ruby",
    "Gemfile": "ruby",
    "Gemfile.lock": "text",
    "Rakefile": "ruby",
    ".php": "php",
    "composer.json": "json",
    "composer.lock": "json",
    ".swift": "swift",
    "Package.swift": "swift",
    ".dart": "dart",
    "pubspec.yaml": "yaml",
    "pubspec.lock": "yaml",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".r": "r",
    ".R": "r",
    ".jl": "julia",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".clj": "clojure",
    ".cljs": "clojure",
    # Shell & Scripts
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "zsh",
    ".fish": "fish",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".bat": "batch",
    ".cmd": "batch",
    # Config & Data
    ".json": "json",
    ".json5": "json",
    ".jsonc": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".xml": "xml",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "ini",
    ".conf": "ini",
    ".config": "ini",
    ".properties": "properties",
    # Docker & Containers
    "dockerfile": "dockerfile",
    "Dockerfile": "dockerfile",
    ".dockerfile": "dockerfile",
    "Dockerfile.dev": "dockerfile",
    "Dockerfile.prod": "dockerfile",
    "Dockerfile.test": "dockerfile",
    "docker-compose.yml": "yaml",
    "docker-compose.yaml": "yaml",
    "docker-compose.dev.yml": "yaml",
    "docker-compose.prod.yml": "yaml",
    "docker-compose.override.yml": "yaml",
    ".dockerignore": "text",
    "compose.yml": "yaml",
    "compose.yaml": "yaml",
    # Kubernetes & Orchestration
    "deployment.yaml": "yaml",
    "deployment.yml": "yaml",
    "service.yaml": "yaml",
    "service.yml": "yaml",
    "ingress.yaml": "yaml",
    "ingress.yml": "yaml",
    "configmap.yaml": "yaml",
    "configmap.yml": "yaml",
    "secret.yaml": "yaml",
    "secret.yml": "yaml",
    "kustomization.yaml": "yaml",
    "kustomization.yml": "yaml",
    "helmfile.yaml": "yaml",
    "Chart.yaml": "yaml",
    "values.yaml": "yaml",
    "values.yml": "yaml",
    # Infrastructure as Code
    ".tf": "hcl",
    ".tfvars": "hcl",
    ".hcl": "hcl",
    "terraform.tfvars": "hcl",
    "variables.tf": "hcl",
    "outputs.tf": "hcl",
    "main.tf": "hcl",
    "Vagrantfile": "ruby",
    # CI/CD
    ".gitlab-ci.yml": "yaml",
    "gitlab-ci.yml": "yaml",
    ".travis.yml": "yaml",
    "travis.yml": "yaml",
    "circle.yml": "yaml",
    ".circleci": "yaml",
    "Jenkinsfile": "groovy",
    "jenkinsfile": "groovy",
    "azure-pipelines.yml": "yaml",
    "azure-pipelines.yaml": "yaml",
    ".drone.yml": "yaml",
    "bitbucket-pipelines.yml": "yaml",
    "appveyor.yml": "yaml",
    ".appveyor.yml": "yaml",
    # GitHub Actions
    "action.yml": "yaml",
    "action.yaml": "yaml",
    # Ansible
    "playbook.yml": "yaml",
    "playbook.yaml": "yaml",
    "ansible.cfg": "ini",
    "hosts": "ini",
    "inventory": "ini",
    # Database
    ".sql": "sql",
    ".psql": "sql",
    ".mysql": "sql",
    ".prisma": "prisma",
    # Docs & Text
    ".md": "markdown",
    ".markdown": "markdown",
    ".txt": "text",
    ".rst": "rst",
    ".adoc": "asciidoc",
    "README": "markdown",
    "CHANGELOG": "markdown",
    "LICENSE": "text",
    "CONTRIBUTING": "markdown",
    # Build & Make
    "makefile": "makefile",
    "Makefile": "makefile",
    "GNUmakefile": "makefile",
    "makefile.am": "makefile",
    # Environment & Config
    ".env": "bash",
    ".env.example": "bash",
    ".env.local": "bash",
    ".env.development": "bash",
    ".env.production": "bash",
    ".env.test": "bash",
    ".env.sample": "bash",
    ".envrc": "bash",
    ".flaskenv": "bash",
    # Git & VCS
    ".gitignore": "text",
    ".gitattributes": "text",
    ".gitmodules": "text",
    ".npmignore": "text",
    ".eslintignore": "text",
    # Editor Config
    ".editorconfig": "ini",
    ".vimrc": "vim",
    ".nvimrc": "vim",
    # GraphQL & API
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".avro": "json",
    ".thrift": "thrift",
    "openapi.yaml": "yaml",
    "openapi.yml": "yaml",
    "swagger.yaml": "yaml",
    "swagger.yml": "yaml",
}

# Patterns to always ignore during file scanning
ALWAYS_IGNORE_PATTERNS: set[str] = {
    # Version Control
    ".git/",
    ".svn/",
    ".hg/",
    ".bzr/",
    # Dependencies
    "node_modules/",
    "bower_components/",
    "jspm_packages/",
    "vendor/",
    "vendors/",
    # Build outputs
    ".next/",
    ".nuxt/",
    ".output/",
    "out/",
    "dist/",
    "build/",
    "target/",
    "_site/",
    ".cache/",
    ".parcel-cache/",
    ".swc/",
    ".turbo/",
    ".vercel/",
    # Python
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".Python",
    ".venv/",
    "venv/",
    "env/",
    "ENV/",
    "virtualenv/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".hypothesis/",
    "*.egg-info/",
    ".tox/",
    ".coverage",
    "htmlcov/",
    ".eggs/",
    "*.egg",
    # Java/JVM
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "hs_err_pid*",
    # Rust
    # Go
    "bin/",
    "pkg/",
    # Ruby
    ".bundle/",
    # IDEs
    ".idea/",
    ".vscode/",
    "*.swp",
    "*.swo",
    "*~",
    ".DS_Store",
    "Thumbs.db",
    ".project",
    ".classpath",
    ".settings/",
    "*.sublime-workspace",
    "*.sublime-project",
    # Logs & Databases
    "*.log",
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    # OS
    "desktop.ini",
    # Misc
    ".env.local",
    ".env.*.local",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "Gemfile.lock",
    "poetry.lock",
    "public/",
    "static/",
    "assets/",
    "media/",
    "uploads/",
}

# File categories for better organization
FILE_CATEGORIES = {
    "source": {
        ".py",
        ".js",
        ".ts",
        ".java",
        ".go",
        ".rs",
        ".rb",
        ".php",
        ".cpp",
        ".c",
        ".cs",
    },
    "config": {".json", ".yaml", ".yml", ".toml", ".ini", ".env", ".config"},
    "docker": {
        "dockerfile",
        "docker-compose.yml",
        "docker-compose.yaml",
        ".dockerignore",
    },
    "iac": {".tf", ".tfvars", ".hcl"},
    "ci_cd": {".gitlab-ci.yml", "Jenkinsfile", "azure-pipelines.yml"},
    "build": {"makefile", "CMakeLists.txt", "build.gradle", "pom.xml"},
    "docs": {".md", ".rst", ".txt"},
}
